[package]
name = "demo-rust-server-licensing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
libloading = "0.8.0"
widestring = "1.0.2"
relative-path = "1.8.0"